[package]
name = "yamaha_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
yamaha_api = { path = "../yamaha_api" }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
anyhow = "1.0.98"